version: '3.8'
services:
  app-node:
    build: .
    container_name: app-node
    ports:
      - "8080:8080"
    environment:
      DYNAMODB_ENDPOINT: "http://host.docker.internal:8000"

  dynamodb-local:
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
      image: "amazon/dynamodb-local:latest"
      container_name: dynamodb-local
      ports:
        - "8000:8000"
      volumes:
        - "./docker/dynamodb:/home/dynamodblocal/data"
      working_dir: /home/dynamodblocal